### ISSUE TITLE
Cannot send data to SUDS in DEV. As an Administrator, I need to be able to send data to SUDS upon accepting an application

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-intake-module#349]
## Notes
I get the following error when trying to accept an application
![image.png](https://images.zenhubusercontent.com/5b16b7b789d5dc41604fe1e0/db58611f-5a60-4109-9c51-a47e486928b9)

## Acceptance Criteria
- [ ] Open Forest can process the information into SUDS (dev)

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
Issue could be related to id of #20. @lauraGgit will check logs. This will not be an issue to production

**Comment by lauraGgit** [comment]
For future reference, the Kibana query to help id this type of error is "@message : ERROR " with an `@cf.app` filter of `fs-middlelayer-api-staging`
